---
server_user: webmaster
server_user_password: webmaster
server_user_ssh_key: "/Users/Username/.ssh/id_rsa.pub"
server_user_home_dir: "/home/{{ server_user }}"

# so that you can access your site at http://vagrant/
# DO NOT add any protocol or forward slashes
wordpress_site_domain: vagrant
wordpress_site_name: Awesome website!

wordpress_admin_user: Superuser
wordpress_admin_password: correcthorsebatterystaple # https://xkcd.com/936/
wordpress_admin_email: user@example.com

wordpress_db_name: wordpress
wordpress_db_username: wordpressuser
wordpress_db_password: password
wordpress_db_encoding: utf8
wordpress_db_collation: utf8_unicode_ci

mysql_root_password: mysql

smtp_email: example@gmail.com # Needs to be Gmail (temporarily)
smtp_password: password
smtp_host: smtp.gmail.com
smtp_port: 587
smtp_domain: example.com

document_root: "/home/{{ server_user }}/www/{{ wordpress_site_domain }}"

ssl: true
ssl_direcory: "/home/{{ server_user }}/certs"
ssl_key: server.key
ssl_cert: server.crt
ssl_dhparam: dhparam.pem
