---
- hosts: all
  sudo: true
  vars_files:
    - vars/development.yml
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - common
    - database
    - webserver
    - monit
    - wordpress
  post_tasks:
    - shell: service nginx reload
