---
- name: 1. Install Monit
  apt: name=monit state=latest

- name: 2. Copy Monit configuration file
  template:
    src: config.j2
    dest: "/etc/monit/conf.d/config"
    mode: 0600

- name: 3. Copy daemon configuration files
  template:
    src: "{{ item }}"
    dest: "/etc/monit/conf.d/{{ item }}"
    mode: 0600
  with_items:
    - hhvm
    - mysql
    - nginx
    - php5-fpm
    - redis
    - system
  notify:
    - restart monit
