---
# These tasks create our new WordPress database and a user that can access it.
- name: Create empty database for WordPress
  mysql_db:
    name: "{{ item.value.wordpress_db_name }}"
    encoding: "{{ item.value.wordpress_db_encoding }}"
    collation: "{{ item.value.wordpress_db_collation }}"
    state: present
  with_dict: wordpress_sites


- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ item.value.wordpress_db_username }}"
    password: "{{ item.value.wordpress_db_password }}"
    host: localhost
    priv: "{{ item.value.wordpress_db_name }}.*:ALL"
    state: present
  with_dict: wordpress_sites
