---
- name: 1. Install MySQL (MariaDB) client and server
  apt: name={{ item }} state=latest
  with_items:
    - python-mysqldb
    - mariadb-client
    - mariadb-server

- name: 2. Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: 3. Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mysql_root_hosts
  changed_when: false

- name: 4. Update MySQL root password for localhost root account.
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items: mysql_root_hosts.stdout_lines

- name: 5. Setup MariaDB creds for root user
  template:
    src: mysql.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: 6. Get list of hosts for the anonymous user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false

- name: 7. Remove anonymous MySQL users.
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: mysql_anonymous_hosts.stdout_lines

- name: 8. Drop MySQL test database
  mysql_db: name=test state=absent
