---
# Install some utilities that all servers benefit from and most of our scripts require
- name: Install common utilities
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - sysvinit-utils # So that 'service' command is accessible
    - unzip # For uncompressing WordPress and plugins
    - imagemagick # Image manipulation
    - git # Source control
    - openjdk-6-jre # Java runtime (if you do YUI asset minification)
    - ssmtp # Simple email sending interface
  sudo: yes

# Copy the SSMTP configuration in place. It's a simple tool to send emails not
# from the server directly but connects to a service such as Gmail in order to send.
- name: Copy SSMTP configuration
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
