---
- name: Install common utilities
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - sysvinit-utils # So that 'service' command is accessible
    - unzip # For uncompressing WordPress and plugins
    - imagemagick # Image manipulation
    - git # Source control
    - openjdk-6-jre # Java runtime (if you do YUI asset minification)
    - ssmtp # Simple email sending interface
  sudo: yes

- name: Copy SSMTP configuration
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
