---
# To install HHVM, we first need to install it's GPG key (as per the documentation)
- name: Install HHVM gpg key
  apt_key: keyserver=keyserver.ubuntu.com id=0x5a16e7281be7a449

- name: Add HHVM deb repository
  apt_repository:
    repo: "deb http://dl.hhvm.com/ubuntu trusty main"
    state: present

- name: Install HHVM packages
  apt: name=hhvm state=latest update_cache=yes

# Override the default configuration so that HHVM listens on a socket, rather
# than a port. Also set the max upload file size in hhvm.ini.j2
- name: Copy HHVM configuration
  template:
    src: hhvm.ini.j2
    dest: /etc/hhvm/server.ini
  notify:
    - restart hhvm
    - restart nginx
