---
- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: Remove default virtual host
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Install the default virtual host
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ wordpress_site_domain }}.conf"

- name: Create certificate directory
  file:
    path: "{{ ssl_direcory }}"
    state: "directory"
    owner: "{{ server_user }}"

- name: Copy certificates into place
  synchronize:
    src: "../certs/{{ item }}"
    dest: "{{ ssl_direcory }}/{{ item }}"
  with_items:
   - "{{ ssl_key }}"
   - "{{ ssl_cert }}"
   - "{{ ssl_dhparam }}"
  when: ssl

- name: Enable new vagrant virtual host
  file:
    src: "/etc/nginx/sites-available/{{ wordpress_site_domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ wordpress_site_domain }}.conf"
    state: link
  notify:
    - reload nginx
