---
# Nginx is our web server of choice. Compared to Apache, it's faster with the
# same resources available, and an increasingly popular choice among sysadmins.
- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: Remove default virtual host
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Install virtual hosts
  template:
    src: "{{ item.key }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.key }}.conf"
  with_dict: wordpress_sites

- name: Create certificate directory
  file:
    path: "{{ ssl_direcory }}"
    state: "directory"
    owner: "{{ server_user }}"

# SSL certificate (and the key) will only be copied if you set the 'ssl'
# variable to 'true'. If you do, make sure you have all the files in place.
- name: Copy certificates into place
  synchronize:
    src: "../certs/{{ item.value.ssl_cert }}"
    dest: "{{ ssl_direcory }}/{{ item.value.ssl_cert }}"
  with_dict: wordpress_sites
  when: item.value.ssl

- name: Copy certificate keys into place
  synchronize:
    src: "../certs/{{ item.value.ssl_key }}"
    dest: "{{ ssl_direcory }}/{{ item.value.ssl_key }}"
  with_dict: wordpress_sites
  when: item.value.ssl

- name: Copy the dhparam pem file
  synchronize:
    src: "../certs/{{ item.value.ssl_dhparam }}"
    dest: "{{ ssl_direcory }}/{{ item.value.ssl_dhparam }}"
  with_dict: wordpress_sites
  when: item.value.ssl

# Copy the WordPress site's virtual host into place and reload Nginx to
# register the settings
- name: Enable new vagrant virtual host
  file:
    src: "/etc/nginx/sites-available/{{ item.key }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.key }}.conf"
    state: link
  with_dict: wordpress_sites
  notify:
    - reload nginx
