---
# Install PHP with all the modules we will need in order for our WordPress to
# function properly.
- name: Install PHP and its modules
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php5
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-mysql
    - php5-xmlrpc
    - php5-redis
